// Licensed under Apache 2.0
// Copyright 2011, National Research Council of Canada
// Property of Lakehead University

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SAVOIR
//  @ File Name : Person.java
//  @ Date : 21/10/2008
//  @ Author : Yosri Harzallah
//
//
package ca.gc.iit.nrc.savoir.domain;

import javax.xml.bind.annotation.XmlType;

@XmlType(name="Participant")
public class Participant {

	/** status is set when the user joins the session **/
	public static final String JOINED = "JOINED";
	/** default status **/
	public static final String NOT_JOINED = "NOT_JOINED";
	
//	Commented out 09-11-2009 by Aaron as part of SM/UM integration
//	/** tutor role **/
//	public static final String TUTOR = "TUTOR";
//	/** student role **/
//	public static final String STUDENT = "STUDENT";	
	
	/** person info **/
	private User user;
	/** person status in the session **/
	private String status;
//	Commented out 09-11-2009 by Aaron as part of SM/UM integration
//	/** person role in the session **/
//	private String role; 
	
	public Participant(){
		
	}
		
	public String toString(){
		return this.getUser().toString();
	}


	public User getUser() {
		return user;
	}


	public String getStatus() {
		return status;
	}

//	Commented out 09-11-2009 by Aaron as part of SM/UM integration
//	public String getRole() {
//		return role;
//	}


	public void setUser(User user) {
		this.user = user;
	}


	public void setStatus(String status) {
		this.status = status;
	}

//	Commented out 09-11-2009 by Aaron as part of SM/UM integration
//	public void setRole(String role) {
//		this.role = role;
//	}
	
}
