// Licensed under Apache 2.0
// Copyright 2011, National Research Council of Canada
// Property of Lakehead University

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SAVOIR
//  @ File Name : TimeSlot.java
//  @ Date : 21/10/2008
//  @ Author : Yosri Harzallah
//
//
package ca.gc.iit.nrc.savoir.domain;

import java.util.Calendar;

import javax.xml.bind.annotation.XmlType;

@XmlType(name="TimeSlot")
public class TimeSlot {
	
	private int id;
	
	private Calendar startTime;
	
	private Calendar endTime;
	
	public TimeSlot(){}
	
	public TimeSlot(Calendar start, Calendar end){
		this.startTime = start;
		this.endTime = end;
	}

	public int getId() {
		return id;
	}

	public Calendar getStartTime() {
		return startTime;
	}

	public Calendar getEndTime() {
		return endTime;
	}

	public void setId(int id) {
		this.id = id;
	}

	public void setStartTime(Calendar startTime) {
		this.startTime = startTime;
	}

	public void setEndTime(Calendar endTime) {
		this.endTime = endTime;
	}
	
	
	
}
